name: Bench2

on:
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Minecraft
        uses: mcenv/setup-minecraft@v3
        with:
          version: "snapshot"
      - name: Benchmark
        run: |
          cd server
          curl -L -o mch.jar https://github.com/mcenv/mch/releases/latest/download/mch.jar
          java -jar mch.jar --mc=$MINECRAFT --time-unit=ns --execute-benchmarks=generic_arity_2:touch_skip,generic_arity_2:touch_check,generic_arity_2:touch_remove
      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: server/mch-results.json
